In [1]:
import numpy as np

## Numpy arrays vs Python lists

In [2]:
array1 = [i for i in range(1, 11)]
array2 = np.arange(1, 11)

print(array1)
print(array2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
print(type(array1), type(array2))

<class 'list'> <class 'numpy.ndarray'>


In [4]:
for i in array1:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [5]:
for i in array2:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [6]:
print(array1 * 2)
print(array2 * 2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
array3 = [2*i for i in range(1, 11)]

print(array3)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [9]:
print(array1 * array3)

TypeError: can't multiply sequence by non-int of type 'list'

In [10]:
print(np.array(array1) * np.array(array3))

[  2   8  18  32  50  72  98 128 162 200]


In [11]:
print(array2 * array3)

[  2   8  18  32  50  72  98 128 162 200]


### Tiling

In [12]:
array4 = np.tile(array2, 3)

print(array4)

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4
  5  6  7  8  9 10]


### Arange, Linspace, Logspace, Zeros, and Ones

In [15]:
start = 50
finish = 100

array5 = np.arange(start, finish + 1, 5.5)

print(array5)

[50.  55.5 61.  66.5 72.  77.5 83.  88.5 94.  99.5]


In [ ]:
start = 0
finish = 5
step = 0.5
number = int((finish - start) / step) + 1

array6 = np.linspace(start, finish, number)

print(array6)

In [16]:
start = 1
finish = 5
number = 5
base = 10

np.logspace(start, finish, number, base)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [17]:
array7 = np.zeros((5, 3))
array8 = np.ones(15, dtype=int)

print(array7)
print(array8)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


### Mathematical Functions

In [18]:
np.pi

3.141592653589793

In [19]:
np.deg2rad(60)

1.0471975511965976

In [20]:
np.rad2deg(np.arccos(0.9))

25.841932763167126

#### Euler's Identity: $e^{i\pi} + 1 = 0$

In [21]:
np.exp(np.pi * 1j) + 1

1.2246467991473532e-16j

### Masking

In [22]:
print(array1)
print(np.mean(array1))

array9 = np.ma.masked_array(array1, mask=[0, 0, 0, 0, 0, 0, 1, 0, 1, 1])
print(array9)
print(np.mean(array9))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
5.5
[1 2 3 4 5 6 -- 8 -- --]
4.142857142857143


In [23]:
mask = np.zeros(10, dtype=int)
print(mask)

np.put(mask, [6, 8, 9], 1)
print(mask)

array10 = np.ma.masked_array(array1, mask=mask)
print(array10)
print(np.mean(array10))

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 1]
[1 2 3 4 5 6 -- 8 -- --]
4.142857142857143


In [24]:
array11 = [i for i in range(1, (18**2) + 1)]
print(array11)

array12 = np.arange(1, (18**2) + 1)
print(array12)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [25]:
array13 = np.random.randint(low=0, high=1000, size=((18**2)))
print(array13)

idx = (array13 >= 500)
print(idx)
print(len(idx))

[190 340 301 325 990 517 265 520 799 898 991 559 753 899 661 212 286 134
  41 418 512 694 879 987 368 837 618 727 727 123 636 870 756 383 285 557
 260 756 945 364 356 172 514 851 908 908 822 246 216 447 643 292 150 606
 999 932 591   3 613 874 727 836 136  38 568 841 748 941 578 797 486 253
  44 727 552 528 600 185 262 183 905 345 990 567 698 817 995 379 400 261
 207 599 102 914 494 574 880 762   1 685  77 695  75 754 139  76 164 188
 798 709  66 278 805 318 294 224 449  49 410 383 258 451 503 403 613 842
 697 847  51   2 303 816 426 802 100 191 840 142 253 633 735 928 272 418
 732 160 770 128 552 482  17 578 230  17  17 561 161  68 173 618 613 705
 592 494 354 651 784 435 161 910  44 615 426 809 761 129 940 636 785 322
 969 735 158 829 916 902 424 860 344 739 838 513 671  27 395 597 837 778
 284 552 786 647 637 454 571 828 891  54 704  56 368 329 387 380 259 711
 160  22 714 174 252 744 467 907 631 239 866 320 757 766 936 204 104 947
 617 876 869 522 549 173 146 528 280 408 428 314 33

In [26]:
print(array11[idx])

TypeError: only integer scalar arrays can be converted to a scalar index

In [27]:
array14 = array12[idx]

print(array14)
print(len(array14))

[  5   6   8   9  10  11  12  13  14  15  21  22  23  24  26  27  28  29
  31  32  33  36  38  39  43  44  45  46  47  51  54  55  56  57  59  60
  61  62  65  66  67  68  69  70  74  75  76  77  81  83  84  85  86  87
  92  94  96  97  98 100 102 104 109 110 113 123 125 126 127 128 132 134
 137 140 141 142 145 147 149 152 156 160 161 162 163 166 167 170 172 174
 175 177 178 179 181 182 184 185 186 188 190 191 192 193 196 197 198 200
 201 202 203 205 206 207 209 216 219 222 224 225 227 229 230 231 234 235
 236 237 238 239 242 248 250 251 252 253 254 256 258 260 264 267 269 270
 271 274 275 280 281 282 288 289 290 291 294 296 297 298 302 304 306 307
 308 309 313 316 318 320 321 322]
170


In [28]:
array15 = np.ma.masked_array(array11, mask=idx)

print(array15)
print(len(array15))

[1 2 3 4 -- -- 7 -- -- -- -- -- -- -- -- 16 17 18 19 20 -- -- -- -- 25 --
 -- -- -- 30 -- -- -- 34 35 -- 37 -- -- 40 41 42 -- -- -- -- -- 48 49 50
 -- 52 53 -- -- -- -- 58 -- -- -- -- 63 64 -- -- -- -- -- -- 71 72 73 --
 -- -- -- 78 79 80 -- 82 -- -- -- -- -- 88 89 90 91 -- 93 -- 95 -- -- --
 99 -- 101 -- 103 -- 105 106 107 108 -- -- 111 112 -- 114 115 116 117 118
 119 120 121 122 -- 124 -- -- -- -- 129 130 131 -- 133 -- 135 136 -- 138
 139 -- -- -- 143 144 -- 146 -- 148 -- 150 151 -- 153 154 155 -- 157 158
 159 -- -- -- -- 164 165 -- -- 168 169 -- 171 -- 173 -- -- 176 -- -- --
 180 -- -- 183 -- -- -- 187 -- 189 -- -- -- -- 194 195 -- -- -- 199 -- --
 -- -- 204 -- -- -- 208 -- 210 211 212 213 214 215 -- 217 218 -- 220 221
 -- 223 -- -- 226 -- 228 -- -- -- 232 233 -- -- -- -- -- -- 240 241 -- 243
 244 245 246 247 -- 249 -- -- -- -- -- 255 -- 257 -- 259 -- 261 262 263 --
 265 266 -- 268 -- -- -- 272 273 -- -- 276 277 278 279 -- -- -- 283 284
 285 286 287 -- -- -- -- 292 293 -- 295 -- -- 

In [29]:
array16 = np.ma.masked_array(array12, mask=idx)

print(array16)
print(len(array16))

[1 2 3 4 -- -- 7 -- -- -- -- -- -- -- -- 16 17 18 19 20 -- -- -- -- 25 --
 -- -- -- 30 -- -- -- 34 35 -- 37 -- -- 40 41 42 -- -- -- -- -- 48 49 50
 -- 52 53 -- -- -- -- 58 -- -- -- -- 63 64 -- -- -- -- -- -- 71 72 73 --
 -- -- -- 78 79 80 -- 82 -- -- -- -- -- 88 89 90 91 -- 93 -- 95 -- -- --
 99 -- 101 -- 103 -- 105 106 107 108 -- -- 111 112 -- 114 115 116 117 118
 119 120 121 122 -- 124 -- -- -- -- 129 130 131 -- 133 -- 135 136 -- 138
 139 -- -- -- 143 144 -- 146 -- 148 -- 150 151 -- 153 154 155 -- 157 158
 159 -- -- -- -- 164 165 -- -- 168 169 -- 171 -- 173 -- -- 176 -- -- --
 180 -- -- 183 -- -- -- 187 -- 189 -- -- -- -- 194 195 -- -- -- 199 -- --
 -- -- 204 -- -- -- 208 -- 210 211 212 213 214 215 -- 217 218 -- 220 221
 -- 223 -- -- 226 -- 228 -- -- -- 232 233 -- -- -- -- -- -- 240 241 -- 243
 244 245 246 247 -- 249 -- -- -- -- -- 255 -- 257 -- 259 -- 261 262 263 --
 265 266 -- 268 -- -- -- 272 273 -- -- 276 277 278 279 -- -- -- 283 284
 285 286 287 -- -- -- -- 292 293 -- 295 -- -- 

### Matrices

In [30]:
a = ['A', '1']
b = ['B', '2']
c = ['C', '3']

array17 = np.matrix([a, b, c])

print(array17)

[['A' '1']
 ['B' '2']
 ['C' '3']]


In [31]:
array18 = array17.transpose()

print(array18)

[['A' 'B' 'C']
 ['1' '2' '3']]
